/*
 * Automatically generated by SVGR from assets/icons/*.svg.
 * Do not edit this file or add other components to this directory.
 */
import type { SVGProps } from 'react'
export function BatteryLevelWiredIcon(
  props: SVGProps<SVGSVGElement>
): JSX.Element {
  return (
    <svg
      xmlns='http://www.w3.org/2000/svg'
      width={24}
      height={25}
      fill='none'
      {...props}
    >
      <mask
        id='battery-level-wired_svg__a'
        width={24}
        height={25}
        x={0}
        y={0}
        maskUnits='userSpaceOnUse'
        style={{
          maskType: 'alpha',
        }}
      >
        <path fill='#D9D9D9' d='M0 .5h24v24H0z' />
      </mask>
      <g mask='url(#battery-level-wired_svg__a)'>
        <path
          fill='#6E7179'
          fillRule='evenodd'
          d='M14.5 18.505a1 1 0 1 0 2 0V15.5h5a1 1 0 1 0 0-2h-5v-3h5a1 1 0 1 0 0-2h-5V5.444a1 1 0 1 0-2 0v.117h-3.576c-2.096 0-3.265 1.922-3.892 3.068-.226.413-.378.518-.548.518H2.51c-1.258 0-2.01.993-2.01 1.96v1.874c0 .967.725 2.195 2.01 2.195h3.996c.21 0 .287.154.405.393.04.082.085.172.142.27.645 1.118 1.817 2.55 3.871 2.55H14.5zm-3.089-2.065c-2.458 0-3.589-3.46-3.589-3.46H2.51v-1.873h5.312s1.131-3.57 3.59-3.57h3.052v8.903z'
          clipRule='evenodd'
        />
      </g>
    </svg>
  )
}
