/*
 * Automatically generated by SVGR from assets/icons/*.svg.
 * Do not edit this file or add other components to this directory.
 */
import type { SVGProps } from 'react'
export function SearchIcon(props: SVGProps<SVGSVGElement>): JSX.Element {
  return (
    <svg
      xmlns='http://www.w3.org/2000/svg'
      width={24}
      height={25}
      fill='none'
      {...props}
    >
      <mask
        id='search_svg__a'
        width={24}
        height={25}
        x={0}
        y={0}
        maskUnits='userSpaceOnUse'
        style={{
          maskType: 'alpha',
        }}
      >
        <path fill='#D9D9D9' d='M0 .988h24v24H0z' />
      </mask>
      <g mask='url(#search_svg__a)'>
        <path
          fill='#232B3A'
          d='m19.6 21.988-6.3-6.3a6.096 6.096 0 0 1-3.8 1.3c-1.817 0-3.354-.629-4.612-1.887C3.629 13.843 3 12.305 3 10.488c0-1.816.63-3.354 1.888-4.613C6.146 4.617 7.683 3.988 9.5 3.988c1.817 0 3.354.63 4.613 1.887C15.371 7.134 16 8.672 16 10.488a6.096 6.096 0 0 1-1.3 3.8l6.3 6.3zm-10.1-7c1.25 0 2.313-.437 3.188-1.312S14 11.738 14 10.488c0-1.25-.437-2.312-1.312-3.188-.875-.874-1.938-1.312-3.188-1.312-1.25 0-2.313.438-3.188 1.312C5.437 8.176 5 9.238 5 10.488c0 1.25.437 2.313 1.312 3.188S8.25 14.988 9.5 14.988'
        />
      </g>
    </svg>
  )
}
